### ISSUE TITLE
Kind request to add the `omero-import` topic

### ISSUE THREAD

**Issue by joshmoore** [Laura190/OMEROimport#1]
cf: https://forum.image.sc/t/setting-up-omero-in-a-new-lab-suggestions-stories-and-advice-welcome/25626/39?u=joshmoore

Hi @Laura190. Would you be willing to add the `omero-import` topic? This will hopefully allow (image.sc) users to more easily find libraries that have been built by the community.

See: https://github.com/topics/omero-import for where it will be listed.

It _might_ be better to add the topic to https://github.com/warwickcamdu/OMEROimport, I'm not sure.

cc: @sbesson @jburel

**Comment by Laura190** [comment]
Hello @joshmoore 
Happy to! I have added the topic to [https://github.com/warwickcamdu/OMEROimport](https://github.com/warwickcamdu/OMEROimport ) since I'm less likely to mess around with that one.

**Comment by joshmoore** [comment]
![Screen Shot 2021-05-12 at 18 39 09](https://user-images.githubusercontent.com/88113/118012452-5da8d280-b351-11eb-92ee-3a1061d941cf.png)

Woo hoo :tada: Thanks for being the first to try this out.
